## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestYAPL

# Rules for building the parser.

AbsYAPL.hs LexYAPL.x ParYAPL.y PrintYAPL.hs TestYAPL.hs : YAPL.cf
	bnfc --haskell YAPL.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestYAPL : AbsYAPL.hs LexYAPL.hs ParYAPL.hs PrintYAPL.hs TestYAPL.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsYAPL.hs AbsYAPL.hs.bak ComposOp.hs ComposOp.hs.bak DocYAPL.txt DocYAPL.txt.bak ErrM.hs ErrM.hs.bak LayoutYAPL.hs LayoutYAPL.hs.bak LexYAPL.x LexYAPL.x.bak ParYAPL.y ParYAPL.y.bak PrintYAPL.hs PrintYAPL.hs.bak SkelYAPL.hs SkelYAPL.hs.bak TestYAPL.hs TestYAPL.hs.bak XMLYAPL.hs XMLYAPL.hs.bak ASTYAPL.agda ASTYAPL.agda.bak ParserYAPL.agda ParserYAPL.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak YAPL.dtd YAPL.dtd.bak TestYAPL LexYAPL.hs ParYAPL.hs ParYAPL.info ParDataYAPL.hs Makefile


# EOF
